<?php

namespace ContainerAPcDMMw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3I6VHZkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3I6VHZk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3I6VHZk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tarea' => ['privates', '.errored..service_locator.3I6VHZk.App\\Entity\\Tarea', NULL, 'Cannot autowire service ".service_locator.3I6VHZk": it needs an instance of "App\\Entity\\Tarea" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'tarea' => 'App\\Entity\\Tarea',
        ]);
    }
}
