<?php

namespace ContainerAPcDMMw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BRiazx9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bRiazx9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bRiazx9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tareaRepository' => ['privates', 'App\\Repository\\TareaRepository', 'getTareaRepositoryService', true],
        ], [
            'tareaRepository' => 'App\\Repository\\TareaRepository',
        ]);
    }
}
