<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAPcDMMw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAPcDMMw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAPcDMMw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAPcDMMw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAPcDMMw\App_KernelDevDebugContainer([
    'container.build_hash' => 'APcDMMw',
    'container.build_id' => '104f2c10',
    'container.build_time' => 1674689390,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAPcDMMw');
