<?php

namespace ContainerXS3NwkI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GuTondService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gu_Tond' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gu_Tond'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tarea' => ['privates', '.errored..service_locator.Gu_Tond.App\\Entity\\Tarea', NULL, 'Cannot autowire service ".service_locator.Gu_Tond": it needs an instance of "App\\Entity\\Tarea" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tarea' => 'App\\Entity\\Tarea',
        ]);
    }
}
