<?php

namespace ContainerXS3NwkI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTareaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Gu_Tond.App\Entity\Tarea' shared service.
     *
     * @return \App\Entity\Tarea
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Gu_Tond": it needs an instance of "App\\Entity\\Tarea" but this type has been excluded in "config/services.yaml".');
    }
}
